AWSTemplateFormatVersion: 2010-09-09
Description: >
  MSP T2 Database Migration 
  AWS Database Migration Service
  Oracle Database to PostgreSQL Database Migration
  "AWS::DMS::ReplicationInstance": MigrationInstance
  "AWS::DMS::Endpoint": SourceEndpoint
  "AWS::DMS::Endpoint": TargetEndpoint
Resources: 
  MigrationInstance:
    Type: "AWS::DMS::ReplicationInstance"
    Properties:
    #Replication instance configuration
      ReplicationInstanceIdentifier: oratopgmig-instance
      ResourceIdentifier: ora2pg
      ReplicationInstanceClass: dms.t3.small
      #EngineVersion: 3.4.7
      AllocatedStorage: 5
      #VpcSecurityGroupIds:
      #  - String
      MultiAZ: false
      PubliclyAccessible: false
    #Advanced security and network configuration
      #ReplicationSubnetGroupIdentifier:
      #AvailabilityZone:
      #KmsKeyId:
    #Maintenance
      #PreferredMaintenanceWindow: Sun:03:00-Sun:05:00
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: false
      #Tags:
      #  - Tag
  SourceEndpoint:
    Type: "AWS::DMS::Endpoint"
    Properties:
    #Endpoint type
      EndpointType: source
    #Endpoint configuration
      EndpointIdentifier: sourcedb
      ResourceIdentifier: sourcedb
      EngineName: oracle
      ServerName: 
      Port: 1521
      Username: hr
      Password: hr
      SslMode: none
      #DatabaseName:
    #Endpoint settings
      ExtraConnectionAttributes: useLogminerReader=N
      #OracleSettings:
      #  OracleSettings
    #KMS Key
      #KmsKeyId:
    #Tags
      #Tags: 
      #  - 
      #    Key: type
      #    Value: new
      #CertificateArn: String
  TargetEndpoint:
    Type: "AWS::DMS::Endpoint"
    Properties:
    #Endpoint type
      EndpointType: target
    #Endpoint configuration
      EndpointIdentifier: targetdb
      ResourceIdentifier: targetdb
      EngineName: 
      ServerName: 
      Port: 
      Username: 
      Password: 
      SslMode: none
      #DatabaseName:
    #Endpoint settings
      #ExtraConnectionAttributes: useLogminerReader=N
      #OracleSettings:
      #  OracleSettings
    #KMS Key
      #KmsKeyId:
    #Tags
      #Tags: 
      #  - 
      #    Key: type
      #    Value: new
      #CertificateArn: String

Outputs:
  InstanceId:
    Description: InstanceId of the newly created RDS Instance
    Value: !Ref MariaDB
  EndpointAddress:
    Description: The connection endpoint for the database
    Value: !GetAtt MariaDB.Endpoint.Address
  EndpointPort:
    Description: The port number on which the database accepts connections
    Value: !GetAtt MariaDB.Endpoint.Port
  InsatancePrivateIP:
    Description: The private IP address of replication instance
    Value: !GetAtt MigrationInstance.ReplicationInstancePrivateIpAddresses

